[tool.poetry]
name = "core"
version = "7.5.1"
description = "CORE Common Open Research Emulator"
authors = ["Boeing Research and Technology"]
license = "BSD-2-Clause"
repository = "https://github.com/coreemu/core"
documentation = "https://coreemu.github.io/core/"
include = [
    "core/api/grpc/*",
    "core/configservices/*/templates",
    "core/constants.py",
    "core/gui/data/**/*",
]
exclude = ["core/constants.py.in"]

# include 是包含 poetry build 没有 init.py 的特殊文件
# 默认执行 poetry install 会包含当前目录至 虚拟python 环境中
# 通过 poetry add/remove/update 包名, 
# 修改 toml 或 手动修改后 需要 poetry update 更新 lock文件

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = { version = "*", python = "~3.6" }
fabric = "2.5.0"
grpcio = "1.27.2"
invoke = "1.4.1"
lxml = "4.5.1"
mako = "1.1.3"
netaddr = "0.7.19"
pillow = "7.1.2"
protobuf = "3.12.2"
pyproj = "2.6.1.post1"
pyyaml = "5.3.1"
selectors = "^0.0.14"

[tool.poetry.dev-dependencies]
black = "==19.3b0"
flake8 = "3.8.2"
grpcio-tools = "1.27.2"
isort = "4.3.21"
mock = "4.0.2"
pre-commit = "2.1.1"
pytest = "5.4.3"

[tool.isort]
skip_glob = "*_pb2*.py,doc,build"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
line_length = 88

[tool.black]
line_length = 88
exclude = ".+_pb2.*.py|doc/|build/|__pycache__/"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

