#!/bin/bash

# 针对特定拓扑场景iperf3-test.imn的流量测试脚本，其服务器配置脚本如下设定
    # #!/bin/sh
    # # auto-generated by IPForward service (utility.py)
    # mkdir -p ../myiperf3log
    # iperf3 -s -D --logfile ../myiperf3log/myiperf3_s$NODE_NUMBER

ipaddr=(
10.0.3.10
10.0.3.11 
10.0.3.12 
10.0.4.10 
10.0.4.11 
10.0.4.12 
10.0.4.13 
10.0.5.10 
10.0.5.11 
10.0.5.12 
10.0.6.10 
10.0.6.11 
10.0.6.12 
10.0.7.10 
10.0.7.11 
10.0.7.12 
10.0.7.13 
10.0.8.10 
10.0.8.11 
10.0.8.12 
)

# for i in $(seq 17 20)   #4组测试
# for i in $(seq 17 24)   #8组测试
# for i in $(seq 17 28)   #12组测试
# for i in $(seq 17 32)   #16组测试
for i in $(seq 17 36)   #20组测试
do 
    index=$i-17
    # cmd="mytcpdump mytest/iperf3-test n$i cmd \"iperf3  -c ${ipaddr[$index]} $* --logfile ../myiperf3log/myiperf3_c$i &\""
    # echo $cmd;
    # mytcpdump mytest/iperf3-test n$i cmd "iperf3  -c ${ipaddr[$index]} $* --logfile ../myiperf3log/myiperf3_c$i &"
    coresendmsg execute node=$i number=1001 command="iperf3  -c ${ipaddr[$index]} $* --logfile ../myiperf3log/myiperf3_c$i &"
done

